@MinimalApi_Sample2_HostAddress = https://localhost:7210


### WeatherForecast
GET {{MinimalApi_Sample2_HostAddress}}/weatherforecast/
Accept: application/json

### Environment Message

GET {{MinimalApi_Sample2_HostAddress}}/message/
Accept: application/json

### User - Get all

GET {{MinimalApi_Sample2_HostAddress}}/users/
Accept: application/json


### Get User - Existing

GET {{MinimalApi_Sample2_HostAddress}}/users/1
Accept: application/json

### Get User - Non-existing

GET {{MinimalApi_Sample2_HostAddress}}/users/5
Accept: application/json


### User - Create

POST {{MinimalApi_Sample2_HostAddress}}/users/
Content-Type: application/json

{
  "name": "Bola",
  "email": "bola@example.com"
}

### User - Update

PUT {{MinimalApi_Sample2_HostAddress}}/users/5
Content-Type: application/json
{
  "id": 5,
  "name": "Oshioriamhe",
  "email": "oshios@example.com"
}

### User - Delete

DELETE {{MinimalApi_Sample2_HostAddress}}/users/3
Content-Type: application/json
